### ISSUE TITLE
Installation Alternatives

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1064]
Check the documentation for the 'Alternatives' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Alternatives page](https://docs.ros.org/en/jazzy/Installation/Alternatives.html)

**Comment by fujitatomoya** [comment]
@marcoag i can check this, please sign me up.

**Comment by fujitatomoya** [comment]
since this issue is labeled with `Ubuntu Noble 24.04`, i did check the procedure https://docs.ros.org/en/jazzy/Installation/Alternatives/Ubuntu-Development-Setup.html and https://docs.ros.org/en/jazzy/Installation/Alternatives/Ubuntu-Install-Binary.html from https://docs.ros.org/en/jazzy/Installation/Alternatives.html

and, no problem observed.

**Comment by fujitatomoya** [comment]
@marcoag we can close this.
