### ISSUE TITLE
Rosdep

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1158]
Check the documentation for the 'Rosdep' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Rosdep page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Rosdep.html)

**Comment by knmcguire** [comment]
You can assign me to this

**Comment by knmcguire** [comment]
_Step 1 - I was able to follow the documentation._
Yes I was

_Step 2 - The documentation seemed clear to me._
Pretty clear to me!

_Step 3 - The documentation didn't have any obvious errors._
Not that I could see. 

Also all code didn't contain errors.

**Seems all okay!**


_Some additional thoughts_ 

This doc seems to be more of an 'concepts' documentation than a tutorial, especially since it doesn't prove an example package to test on so it is mostly just explaining the concepts.
