### ISSUE TITLE
Quaternion Fundamentals

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1169]
Check the documentation for the 'Quaternion Fundamentals' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Quaternion Fundamentals page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Tf2/Quaternion-Fundamentals.html)

**Comment by samuel-ongzx** [comment]
## Process
- [x] Step 1 - I was able to follow the documentation.
- [x] Step 2 - The documentation seemed clear to me.
- [x] Step 3 - The documentation didn't have any obvious errors.

## Tested
Tested [Link](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Tf2/Quaternion-Fundamentals.html#quaternion-types-in-ros-2)
- [x] Components of a quaternion (`ok` - no problem in syntax for C++ quaternions, built C++ and ran without issues)
- [x] Quaternion Types in ROS2 (`ok` - both C++ & python, conversion ok for C++ built and ran, no issues for import in Python able to run too)
- [x] Quaternion operations (`ok` - C++ & python scripts works, inversion & relative transformation math are also verified to be correct)

P.S. no screenshots / images since my test scripts are all very haphazard :(

**Comment by marcoag** [comment]
thanks!
