### ISSUE TITLE
Building ROS2 Package with eclipse 2021 06

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#945]
Check the documentation for the 'Building ROS2 Package with eclipse 2021 06' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Building ROS2 Package with eclipse 2021 06 page](https://docs.ros.org/en/iron/Tutorials/Miscellaneous/Building-ROS2-Package-with-eclipse-2021-06.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by karmenlu** [comment]
I'll take this one.

**Comment by iuhilnehc-ynos** [comment]
* [ ]  **I was able to follow the documentation.**
* [ ]  **The documentation seemed clear to me.**
* [ ]  **The documentation didn't have any obvious errors.**

Issues:

- `ROS 2 includes` could not be resolved with `/opt/ros/iron/include`
  I need to use paths of separate packages. e.g. `/opt/ros/iron/include/rclcpp`, `/opt/ros/iron/include/std_msgs`.
- Build successfully, but
  Eclipse uses `colcon` to build `/home/ros2/dev_ws` rather than the current package(`/home/ros2/eclipse-workspace/my_package`) in the workspace, which means if I update the source code with Eclipse and then build again, it can't be effective.
  The reason is that the package is imported with a copy operation, not with a link.

<details><summary> log </summary>
<p>

- ROS 2 includes got resolved (NG)
![image](https://github.com/osrf/ros2_test_cases/assets/64191023/579d3043-cf46-42d0-bb3f-99bc807df1c2)
![image](https://github.com/osrf/ros2_test_cases/assets/64191023/8cbf51c6-f9b3-49b3-bfe8-1af9b5cbb8bd)
The header files are installed with [DESTINATION include/${PROJECT_NAME}](https://github.com/ros2/rclcpp/blob/a7048e115d9316b54161180fa3bddab29bce7cc3/rclcpp/CMakeLists.txt#L265)
![image](https://github.com/osrf/ros2_test_cases/assets/64191023/701cef79-fe38-418d-a08f-95b30d3b58dd)

- Import files without using a link, but to build for another working directory
![image](https://github.com/osrf/ros2_test_cases/assets/64191023/a09504f5-aaab-4c50-ba1b-321a967cb3bd)
![image](https://github.com/osrf/ros2_test_cases/assets/64191023/efe3b960-9798-40f4-8623-4cff82f4f4ac)


</p>
</details>

**Comment by iuhilnehc-ynos** [comment]
@karmenlu, I just shared my test. 

I appreciate that if you could review and confirm the document as well.

**Comment by Yadunund** [comment]
@iuhilnehc-ynos thanks for testing this out! Nice catch of the discrepancy between the name of the workspace in the first screenshot and the working directory set later on. And also the point about having to add include paths for each package separately.

Do you mind opening a PR to update the page on ros2_documentation?

**Comment by iuhilnehc-ynos** [comment]
> Do you mind opening a PR to update the page on ros2_documentation?

No, I'd love to.

**Comment by Yadunund** [comment]
Awesome, will close this out.
